# Generated by Django 3.1.3 on 2020-11-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_of_contract', models.CharField(max_length=15)),
                ('date_of_contract', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=40)),
                ('name_of_organization', models.CharField(max_length=255)),
                ('in_face', models.CharField(help_text='"In face" in parental case', max_length=40)),
                ('in_face_in_nominative', models.CharField(help_text='"In face" in nominative', max_length=40)),
                ('name_face_organizations', models.CharField(help_text='Full Name in parental case', max_length=255)),
                ('acting_on_the_basis', models.CharField(max_length=255)),
                ('legal_address', models.TextField()),
                ('unp', models.CharField(max_length=9)),
                ('initials', models.CharField(max_length=50)),
            ],
        ),
    ]
