# Generated by Django 3.1.3 on 2020-11-30 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_docx', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address_of_bank',
            field=models.TextField(blank=True, null=True),
        ),
    ]
