# Generated by Django 3.1.3 on 2020-12-08 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_docx', '0004_auto_20201202_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='phone_number',
            field=models.CharField(blank=True, default=1, max_length=13),
            preserve_default=False,
        ),
    ]
