# Generated by Django 3.1.3 on 2020-12-09 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_docx', '0005_auto_20201208_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_creation', models.CharField(max_length=15)),
                ('number_document', models.CharField(max_length=3)),
            ],
        ),
    ]
