# Generated by Django 3.1.3 on 2020-12-17 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generate_docx', '0006_fileclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileclient',
            name='name_of_document',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
